export { default as T } from './components/T.vue'
export { default as t } from './composables/t'
export { default as useI18n } from './composables/useI18n'
export { default as useLocale } from './composables/useLocale'
export { default as createPsitta } from './createPsitta'
